### ISSUE TITLE
Bootgly Template Engine - Roadmap Checklist

### ISSUE THREAD

**Issue by rodrigoslayertech** [bootgly/bootgly#7]
Namespace:
`Bootgly\ABI\Templates\Template`

#### Ifs
- [x] Simple Ifs (`@if`, `@elseif`, `@else`)
- [x] Short syntax in Ifs for `!empty` and `isSet`
#### Switchs
- [x] Switch

#### Echos
- [x] Prepending break line echo (`@.>`)
- [x] Append break line echo (`@>.`)
- [x] Wrap break line echo (`@.>.`)
- [x] Simple echo (`@>`)

### Escapes
- [x] Inline escape (`@@`)

#### Whiles
- [x] Only While
- [x] While with `@break`
- [x] While with `@continue`
- [x] While with `@break in ...` (conditional break)
- [x] While with `@continue in ...` (conditional continue)
#### Foreachs
- [x] Foreach
- [x] Foreach with Metavar (`$@`)
- [x] Foreach with Metavar and nested support
#### For
- [x] For

### Raw
- [x] PHP Code (`@:...@;`)

### Precompilers
- [x] Unident
### Postcompilers
- [x] Join <?php tags

## Debugging
- [x] Set Path of Template file as comment token
